### ISSUE TITLE
Jump Pager

### ISSUE THREAD

**Issue by ppamorim** [alexzaitsev/freepager#1]
Will be interest to implement a possibility to jump the pages.
Today, ViewPager work like this:
[1] -> [2] -> [3]

We need recreate this:
[1] -> [3] -> [2]

Stack the fragments will be a good ideia. What do you thinks?
[1] -> [n]

**Comment by alexzaitsev** [comment]
> Today, ViewPager work like this:
> [1] -> [2] -> [3]
> 
> We need recreate this:
> [1] -> [3] -> [2]

It is built on `ViewFactory` concept. How the next page will look like depends on what `ViewFactory` returns. 
In the simpliest way you can do some `mapper` Position->View:

```
@Override
public View makeView(int vertical, int horizontal) {
    ViewPosition vp = viewMapper.getNormalizedPos(vertical, horizontal);
    return getViewByPos(vp);
}
```

Parameters:
///
vertical = 0, horizontal = 1
vp.vertical = 0, vp.horizontal = 1
///
vertical = 0, horizontal = 2
vp.vertical = 0, vp.horizontal = 3
///
vertical = 0, horizontal = 3
vp.vertical = 0, vp.horizontal = 2
///

> Stack the fragments will be a good ideia. What do you thinks?

That's great idea but unfortunately I haven't much free time right now. Maybe you want to implement this feature - feel free to make pull request.
