### ISSUE TITLE
How to use horizontal view to display list view item in listview

### ISSUE THREAD

**Issue by anchitjindal91** [alexzaitsev/freepager#2]
Hi for a requirement i am referring your code its really very good example can you please help me how can i use it with dynamic data. In my task i have list of user which i need to show in list view(vertically) and each users have multiple images which i want to show horizontally. Thanks

**Comment by gauravsaini03-zz** [comment]
@alexzaitsev : Also, created an question on StackOverflow. Can you please help us out :)
http://stackoverflow.com/questions/31936319/android-download-list-of-images-and-show-images-in-viewpager-with-progress-dialo/31936614?noredirect=1#comment51911494_31936614
