### ISSUE TITLE
set position programmatically

### ISSUE THREAD

**Issue by mohamadk** [alexzaitsev/freepager#4]
Hi Alex thanks for this very nice library
I use your library and I want to set current item programmatically. 
for that I use this code:
horizontalViewpager.setCurentitem(horizontalViewpager.getCurentItem()+3);
but it's not working and my app going to not responding page in android.  
is there any way to go to a page programmatically?

**Comment by alexzaitsev** [comment]
Hi @mohamadk. If this is issue is actual please share some code so I can help you

**Comment by mohamadk** [comment]
Hi alex sorry for response too late.
btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                pager.setCurrentItem(verticalPager.getCurrentItem()+3);
            }
        });
add this code in your view factory of infinite horizontal pager then click on a button. you will see app going to not responding page. at least in my case htc desire 200.
and I can't find a way to set current page in vertical pager can you suggest me a way about that too?

**Comment by alexzaitsev** [comment]
@mohamadk You see, this library doesn't have this feature. Unfortunately I can't give you some quick workaround. My advice: try to avoid such views as this, it doesn't match to Google guidelines and can be unfrendly to user. 
Tip: you can replace this view with simple `GridView` and arrows. Maybe not the best solution but much predictable and supportable.
